const quotes = [
  '“And, when you want something, all the universe conspires in helping you to achieve it.” – Paulo Coelho',
  '“Not all those who wander are lost.” – J.R.R. Tolkien',
  '“You must have chaos within you to give birth to a dancing star.” – Friedrich Nietzsche',
  '“The wound is the place where the Light enters you.” – Rumi',
  '“Do not go gentle into that good night. Rage, rage against the dying of the light.” – Dylan Thomas',
  '“Even the darkest night will end and the sun will rise.” – Victor Hugo',
  '“There is a crack in everything, that’s how the light gets in.” – Leonard Cohen',
  '“To live is the rarest thing in the world. Most people exist, that is all.” – Oscar Wilde',
  '“Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.” – Langston Hughes',
  '“I took the one less traveled by, and that has made all the difference.” – Robert Frost',
  '“We are all in the gutter, but some of us are looking at the stars.” – Oscar Wilde',
  '“The only way to make sense out of change is to plunge into it, move with it, and join the dance.” – Alan Watts',
  '“Don’t count the days, make the days count.” – Muhammad Ali',
  '“We must be willing to let go of the life we planned so as to have the life that is waiting for us.” – Joseph Campbell',
  '“The best way out is always through.” – Robert Frost',
  '“Every saint has a past, and every sinner has a future.” – Oscar Wilde',
  '“The soul would have no rainbow if the eyes had no tears.” – Native American Proverb',
  '“He who opens a school door, closes a prison.” – Victor Hugo',
  '“You do not find the happy life. You make it.” – Camilla Eyring Kimball',
  '“Happiness is not by chance, but by choice.” – Jim Rohn',
  '“No one can make you feel inferior without your consent.” – Eleanor Roosevelt',
  '“A journey of a thousand miles begins with a single step.” – Lao Tzu',
  '“Let yourself be silently drawn by the strange pull of what you really love.” – Rumi',
  '“Live as if you were to die tomorrow. Learn as if you were to live forever.” – Mahatma Gandhi',
  '“Success is not final, failure is not fatal: it is the courage to continue that counts.” – Winston Churchill',
  '“Everything you can imagine is real.” – Pablo Picasso',
  '“Be yourself; everyone else is already taken.” – Oscar Wilde',
  '“Whatever you are, be a good one.” – Abraham Lincoln',
  '“You miss 100% of the shots you don’t take.” – Wayne Gretzky',
  '“Be fearless in the pursuit of what sets your soul on fire.” – Jennifer Lee',
  '“Turn your wounds into wisdom.” – Oprah Winfrey',
  '“It is never too late to be what you might have been.” – George Eliot',
  '“What lies behind us and what lies before us are tiny matters compared to what lies within us.” – Ralph Waldo Emerson',
  '“Courage is grace under pressure.” – Ernest Hemingway',
  '“Believe you can and you’re halfway there.” – Theodore Roosevelt',
  '“A smooth sea never made a skilled sailor.” – Franklin D. Roosevelt',
  '“Stars can’t shine without darkness.” – D.H. Sidebottom',
  '“Be a voice, not an echo.” – Albert Einstein',
  '“Throw kindness around like confetti.” – Unknown',
  '“The sky is not the limit. Your mind is.” – Lynette Simeone',
  '“Doubt kills more dreams than failure ever will.” – Suzy Kassem',
  '“Be the change that you wish to see in the world.” – Mahatma Gandhi',
  '“In the middle of difficulty lies opportunity.” – Albert Einstein',
  '“You are enough just as you are.” – Meghan Markle',
  '“What you get by achieving your goals is not as important as what you become by achieving your goals.” – Zig Ziglar',
  '“Don’t watch the clock; do what it does. Keep going.” – Sam Levenson',
  '“The only limit to our realization of tomorrow is our doubts of today.” – Franklin D. Roosevelt',
  '“Success usually comes to those who are too busy to be looking for it.” – Henry David Thoreau',
  '“Try to be a rainbow in someone’s cloud.” – Maya Angelou',
  '“Great things never come from comfort zones.” – Neil Strauss',
  '“You don’t have to see the whole staircase, just take the first step.” – Martin Luther King Jr.',
  '“Creativity is intelligence having fun.” – Albert Einstein',
  '“The mind is everything. What you think you become.” – Buddha',
  '“Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.” – Roy T. Bennett',
  '“Do what you can, with what you have, where you are.” – Theodore Roosevelt',
  '“Wake up with determination. Go to bed with satisfaction.” – Unknown',
  '“Little by little, one travels far.” – J.R.R. Tolkien',
  "“Shoot for the moon. Even if you miss, you'll land among the stars.” – Norman Vincent Peale",
  '“Your life does not get better by chance, it gets better by change.” – Jim Rohn',
  '“It always seems impossible until it’s done.” – Nelson Mandela',
  '“Don’t limit your challenges. Challenge your limits.” – Jerry Dunn',
  '“Work hard in silence, let your success be your noise.” – Frank Ocean',
  '“Dream big and dare to fail.” – Norman Vaughan',
  '“You are stronger than you think.” – Unknown',
  '“A diamond is a chunk of coal that did well under pressure.” – Henry Kissinger',
  '“Act as if what you do makes a difference. It does.” – William James',
  '“If opportunity doesn’t knock, build a door.” – Milton Berle',
  '“Be so good they can’t ignore you.” – Steve Martin',
  '“Magic is believing in yourself.” – Johann Wolfgang von Goethe',
  '“Don’t settle for what life gives you; make life better and build something.” – Ashton Kutcher',
  '“There is nothing impossible to they who will try.” – Alexander the Great',
  '“Learn as if you will live forever, live like you will die tomorrow.” – Mahatma Gandhi',
  '“Stay foolish to stay sane.” – Maxime Lagacé',
  '“Don’t tell people your plans. Show them your results.” – Unknown',
  '“If you want it, work for it.” – Unknown',
  '“The harder you work for something, the greater you’ll feel when you achieve it.” – Unknown',
  '“Success is what comes after you stop making excuses.” – Luis Galarza',
  '“Sometimes we’re tested not to show our weaknesses, but to discover our strengths.” – Unknown',
  '“The key to success is to focus on goals, not obstacles.” – Unknown',
  '“Dream it. Wish it. Do it.” – Unknown',
  '“You only fail when you stop trying.” – Albert Einstein',
  '“The way to get started is to quit talking and begin doing.” – Walt Disney',
  '“You don’t need to see the whole path. Just take the next step.” – Unknown',
  '“Effort is the spark that ignites your potential.” – Unknown',
  '“Keep going. Everything you need will come to you.” – Unknown',
  '“Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don’t belong.” – Mandy Hale',
  '“Do something today that your future self will thank you for.” – Sean Patrick Flanery',
  '“Pain is temporary. Quitting lasts forever.” – Lance Armstrong',
  '“Don’t be afraid to give up the good to go for the great.” – John D. Rockefeller',
  '“Fall seven times, stand up eight.” – Japanese Proverb',
  '“Life is either a daring adventure or nothing at all.” – Helen Keller',
  '“Push yourself, because no one else is going to do it for you.” – Unknown',
  '“Dare to dream, dare to fly, dare to be the ever chosen sky.” – Unknown',
  '“Live life like a poem—rhythmic, raw, and real.” – Unknown',
];

// Function to get two random, non-repeating quotes
function generateQuote() {
  let index1 = Math.floor(Math.random() * quotes.length);
  let index2;
  do {
    index2 = Math.floor(Math.random() * quotes.length);
  } while (index2 === index1);

  const quoteDisplay = document.getElementById('quote');
  quoteDisplay.innerHTML = `
    <p>${quotes[index1]}</p>
    <p>${quotes[index2]}</p>
  `;
}
